//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplodocus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DDB_DIPLODOCUSEntities : DbContext
    {
        public DDB_DIPLODOCUSEntities()
            : base("name=DDB_DIPLODOCUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
       // public virtual DbSet<Examen> Examen1 { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<SchoolSubject> SchoolSubjects { get; set; }
        //public virtual DbSet<SchoolSubjectMark> SchoolSubjectMarks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<StudentMarkSubject> StudentMarkSubjects { get; set; }
    }
}
