//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplodocus
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMarkSubject
    {
        public int IdStudentMarkSubject { get; set; }
        public int Student_idUser { get; set; }
        public int SchoolSubject_idSubject { get; set; }
        public int SchoolSubjectMarkIdMark { get; set; }
    
        public virtual Student unStudent { get; set; }
        public virtual SchoolSubject aSchoolSubject { get; set; }
        public virtual SchoolSubjectMark aSchoolSubjectMark { get; set; }
    }
}
