//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplodocus
{
    using System;
    using System.Collections.Generic;
    public partial class Student
    {
        private Dictionary<Student, SchoolSubjectMark> lesFormations;

        public int idUser { get; set; }

        public virtual User User { get; set; }

        public Student()
        {

            lesFormations = new Dictionary<Student, SchoolSubjectMark>;
        }

        public void addMark(SchoolSubject uneMatiere, Student unStudent)
        {
        
        }

        public Dictionary<Student, SchoolSubjectMark> getMark()
        {

            return lesFormations;
        }

        public void setMark(Student unStudent)
        {

        }
    }
}
