// <auto-generated />
namespace Diplodocus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210755283_27"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
