// <auto-generated />
namespace Diplodocus.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class merd3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merd3));
        
        string IMigrationMetadata.Id
        {
            get { return "201806251326372_merd3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
